plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.140'
}

version = mod_version
group = 'xfacthd.contex'

base {
    archivesName = 'ConnectedTextures'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets {
    main.resources {
        srcDir "src/generated/resources"
    }
    testdata {
        java {
            srcDir "src/testdata/java"
            compileClasspath += main.output
            runtimeClasspath += main.output
        }
        resources {
            srcDir "src/testdata/resources"
        }
    }
}

neoForge {
    version = project.neoforge_version

    runs {
        configureEach {
            //systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'terminal.ansi', 'true'
            systemProperty 'contex.force_builtin', 'true'

            sourceSet = project.sourceSets.testdata
        }

        client {
            client()
            gameDirectory = project.file('run')
        }

        server {
            server()
            gameDirectory = project.file('run_server')

            programArgument '--nogui'
        }

        data {
            clientData()
            gameDirectory = project.file('run')

            programArguments.addAll(
                    '--mod', 'contex',
                    '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath()
            )
        }
    }

    mods {
        contex {
            sourceSet(project.sourceSets.main)
            sourceSet(project.sourceSets.testdata)
        }
    }

    addModdingDependenciesTo(project.sourceSets.testdata)
}

jar {
    exclude("/.cache")
    exclude('/test_ct')
}

repositories {
    maven {
        name = 'CurseMaven'
        url = 'https://www.cursemaven.com'
        content {
            includeGroup('curse.maven')
        }
    }
}

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
// The dependency is so local that the used classpath must be from the
// sourceset specified in the run config and not a parent thereof
configurations {
    testRuntimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly("curse.maven:atlasviewer-633577:${atlasviewer_coord}")
    localRuntime("curse.maven:atlasviewer-633577:${atlasviewer_coord}")
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version: neoforge_version,
            neoforge_version_range: neoforge_version_range,
            mod_version: mod_version,
            atlasviewer_version: atlasviewer_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

processTestdataResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

publishing {
    publications {
        register ('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << "-Xmaxerrs" << "10000"
}
