modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL v3"
issueTrackerURL="https://github.com/XFactHD/ConnectedTextures"

[[mods]]
	modId="contex"
	version="${mod_version}"
	displayName="ConnectedTextures"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	#displayURL="https://www.curseforge.com/minecraft/mc-mods/connectedtextures"
	logoFile="logo.png"
	authors="XFactHD"
	displayTest="IGNORE_ALL_VERSION"
	description='''
	'''

[[dependencies.contex]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.contex]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
