license="LGPL v3"
issueTrackerURL="https://github.com/XFactHD/ConnectedTextures"

[[mods]]
	modId="contex"
	version="${mod_version}"
	displayName="ConTex"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/contex"
	iconFile="icon.png"
	authors="XFactHD"
	description='''Yet another connected textures mod'''

[[dependencies.contex]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.contex]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="atlasviewer"
    type="optional"
    versionRange="[${atlasviewer_version},)"
    ordering="NONE"
    side="CLIENT"
